---
- name: Install Kibana in CentOS
  yum:
    name: kibana
    state: present
  when: ansible_distribution == "CentOS"

- name: Install Kibana in Ubuntu
  apt:
    name: kibana
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
